# Mathematical functions in python

In [2]:
import numpy as np

In [3]:
m1 = np.matrix([[1,2,3],[5,6,7],[7,8,9]])

In [4]:
m2 = np.matrix([[4,5,6],[7,8,9],[2,3,4]])

In [5]:
# for dot product 
np.dot(m1,m2)

matrix([[ 24,  30,  36],
        [ 76,  94, 112],
        [102, 126, 150]])

In [6]:
# for matrix multiplication
m1*m2

matrix([[ 24,  30,  36],
        [ 76,  94, 112],
        [102, 126, 150]])

In [7]:
a1 = np.matrix([1,2,3,4,5])
a2 = np.matrix([6,7,8,9,10])
a1*a2
#this throws an error as the matrix to be multiplied are not compatible,i.e the columns of first are not equal to rows of second

ValueError: shapes (1,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)

In [ ]:
# we can perform such operation on vectors i.e. arrays without dimention compatibility

In [8]:
# to find the rank of the matrix , we can use linear algebra module of numpy
np.linalg.matrix_rank(m1)

2

In [26]:
arr  = np.matrix([[1,3,5],[2,4,6],[12,10,15]])
arr

matrix([[ 1,  3,  5],
        [ 2,  4,  6],
        [12, 10, 15]])

In [27]:
np.linalg.det(arr)

-14.000000000000009

In [28]:
m1

matrix([[1, 2, 3],
        [5, 6, 7],
        [7, 8, 9]])

In [30]:
np.linalg.matrix_rank(m1)        # signifies that its a singular matrix, i.e the determinant of this matrix is zero.

2

In [31]:
np.linalg.det(m1)         # this gives incorrect result , the answer should have been 0.
# tthis inaccuracy is on account of representation of floating point numbers in memory.
# we can see that the error is so close to zero , negligible and can be ignored.

-4.060244204343427e-15