# NUMPY arrays


In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3])

In [5]:
arr*3

array([3, 6, 9])

In [6]:
arr**3

array([ 1,  8, 27], dtype=int32)

In [8]:
arr.dtype

dtype('int32')

In [9]:
arr.ndim

1

In [10]:
arr.shape

(3,)

In [11]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
arr.shape

(3, 3)

In [13]:
arr.ndim

2

In [14]:
type(arr)

numpy.ndarray

In [25]:
n_array = np.arange(1000)

In [27]:
p_array = list(range(1000))

In [28]:
# 'arange function in numpy is similar to range in python , the difference is that , range returs a type range object 
# while numpy arange returns an array of range.

In [29]:
# lets compare the timing of two similar operations using numpy and simple python functions using '%timeit'

In [31]:
%timeit [i**3 for i in p_array]

712 µs ± 66.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [32]:
%timeit n_array**3

6.46 µs ± 89 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [33]:
# so we can see from above that the numpy array is more than 100 times faster than python array

In [34]:
# we can also create matrices automstically using numpy array

In [37]:
# lets take another example of multiplying these lists and noting their time

In [44]:
p_square = [i**2 for i in p_array]

In [45]:
n_square = [n_array**2]

In [46]:
%timeit list(map(lambda x,y : x*y , p_array, p_square ))

233 µs ± 3.45 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [47]:
%timeit n_array * n_square

8.14 µs ± 43.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [49]:
np.arange(2,30,3)      # 'arange' syantax ---- np.arange(start,end,jump)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [51]:
list(range(2,30,3))   # basically the same syntax

[2, 5, 8, 11, 14, 17, 20, 23, 26, 29]

In [55]:
# for automatically creating matrices sysntax --- np.full((rows,columns),value)
np.full((3,3),0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [56]:
np.full((3,2), 4)

array([[4, 4],
       [4, 4],
       [4, 4]])

In [61]:
# for identity matrix
np.eye(3, dtype = np.int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [63]:
# for diagonal matrix   syntax --- np.diag(List) or np.diag([values])
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [64]:
v = np.array([1,2,3])

In [67]:
# to make a matrix which contains this above matrix 'v' as a submatrix u can use tile function--- np.tile(matrix,(rows, columns))
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [68]:
np.tile(v,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [69]:
np.tile(v,(3,0))

array([], shape=(3, 0), dtype=int32)

In [70]:
# to get a random number in numpy between zero and one we have np.random.random()

In [75]:
np.random.random()

0.30175765342339333

In [73]:
# to make matrix of random values
np.random.random((3,3))

array([[0.00195416, 0.76812287, 0.7333744 ],
       [0.59225371, 0.28521324, 0.08146341],
       [0.27004007, 0.95134154, 0.46282346]])