# Numpy other functions

In [5]:
# To create a list containing n number of equally spaced items between 2 numbers a and b use function 'np.inspace(a,b,n)'

In [5]:
import numpy as np

In [7]:
arr = np.linspace(1,100,50)

In [8]:
arr

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [10]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [11]:
a.shape

(12,)

In [12]:
# we can reshape this array to chane its dimentions , if we dont know what to put as dimentions then we can simply put one 
# dimention and put othe other one as '-1' ,numpy will automaticaly find the second one.
b = a.reshape(2,3,-1)

In [13]:
b

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [16]:
b = a.reshape(3,4)

In [17]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
# to get the value at multiple indices , use a list of indices as index as shown below
a[[1,3,5,7,9,11]]

array([ 2,  4,  6,  8, 10, 12])

In [24]:
# for a single index value 
a[4]

5

In [25]:
# splitting numpy arrays is same as splitting lists, syntax --- array[start:end:jump]
a[0:3:2]

array([1, 3])

In [26]:
# observe and analyse from this point onwards
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
print(arr[2,2],arr[0,0],arr[1,0])

9 1 4


In [32]:
# we can impose a condition on whole array collectively and it will result in a boolean array accordingly
arr >5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [33]:
# we can use this boolean array obtained to do something else like making new matrix , or printing elements , or doing operationson them etc.
print(arr[arr>5])

[6 7 8 9]


In [41]:
new_arr = arr[arr>5]*10

In [42]:
new_arr

array([60, 70, 80, 90])

In [43]:
# copying a np arrray
b = arr

In [45]:
np.shares_memory(arr,b) # This return if the two arrays shares the same memory loction

True

In [47]:
# to make a separate copy use copy()function
b = arr.copy()

In [49]:
np.shares_memory(arr,b)    # now a separate and independent copy of arr is made

False

In [6]:
a = np.array([[1,2,3],[4,5,6]])

In [51]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# to get the transpose of array 'a', we do
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
b = np.array([[7,8,9],[10,11,12]])

In [10]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [13]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [14]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [18]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [19]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [20]:
np.sum(a)

21

In [24]:
a.sum()       # both of them works... try one then another

21

In [25]:
np.median(a)

3.5

In [29]:
np.mean(a)

3.5

In [32]:
a.std()      # standard deviation

1.707825127659933

In [35]:
det = np.array([[2,3,4],[3,4,5],[4,5,6]])

In [36]:
# for finding the determinant of square matrix , we will use liner algebra module of numpy
np.linalg.det(det)

0.0

In [39]:
# for finding inverse of a matrix we can do, here we get an error as shown below because the matrix is singular
np.linalg.inv(det)

LinAlgError: Singular matrix

In [41]:
det = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [42]:
np.linalg.inv(det)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [44]:
matrix = np.array([[1,-2],[-5,4]])

In [51]:
# for finding eigen values and eigen vectors
eigen_values, eigen_vector = np.linalg.eig(matrix)

In [52]:
eigen_values, eigen_vector

(array([-1.,  6.]), array([[-0.70710678,  0.37139068],
        [-0.70710678, -0.92847669]]))

In [58]:
# for dot product of vectors
a = np.array([[1,2],[2,3]])
b = np.array([[4,5],[6,7]])

In [59]:
np.dot(a,b)

array([[16, 19],
       [26, 31]])

In [62]:
# we can also sepcify the data type of array
new = np.array([1,2,0,4,5], dtype = bool)

In [61]:
new

array([ True,  True,  True,  True,  True])

In [64]:
new2 = new.copy()
new2[0] = 0
new2

array([False,  True, False,  True,  True])

In [65]:
new or new2         #this doesnt work

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [68]:
np.logical_or(new,new2)     # This does


array([False,  True, False,  True,  True])

In [69]:
new == new2

array([False,  True,  True,  True,  True])

In [70]:
# if you want to check if all the values are equal or not then u can use 
np.all(new == new2)

False

In [81]:
# for max value in matrix
a = np.array([[1,2],[3,4]])

In [82]:
a.max()

4

In [83]:
# for the index of max value , do this
a.argmax()

3

In [84]:
arr = np.arange(10)

In [85]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
arr.shape

(10,)

In [94]:
# to add a new dimention in this array we can use, please see its github reference "https://stackoverflow.com/questions/29241056/how-does-numpy-newaxis-work-and-when-to-use-it"
print(arr[:,np.newaxis])
arr[:,np.newaxis].shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


(10, 1)